### ISSUE TITLE
Fall back for turfjs and Mapboxjs

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#323]
We use mapboxjs to display the pretty map of Brigades and turfjs to help people find their local group.

Mapbox only works in IE9+ and I bet turfjs is the same.

Problem is, we still get 12% of traffic from people on their City Hall computers using IE8.
![screen shot 2015-04-15 at 12 02 47 pm](https://cloud.githubusercontent.com/assets/595778/7167133/8a97d572-e367-11e4-811f-418c42394fee.png)

We should build a fallback or something for these users. Not really a polyfill, more like just show a list of Brigades and dont do a nearest search.

**Comment by tdooner** [comment]
Thankfully, times have changed and IE usage is negligible now.
