### ISSUE TITLE
New routes to cover old brigade links

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#324]
#### Description
The old Brigade site had urls like /brigade/index/Code-for-San-Francisco for individual Brigades. We've dropped the "/index" part for the new site. We should still support these old urls though as they are in the wild.

#### Files
app.py

#### Tasks
- [ ] Write tests for old urls being routed to new templates
- [ ] Write a new route that catches everything at `/brigade/index/<brigadeid>/`

**Comment by migurski** [comment]
I’d call this pretty high priority, since all these links are currently dead.
