### ISSUE TITLE
Turning National Day banner into a better call out

### ISSUE THREAD

**Issue by Jaime-Alexis** [codeforamerica/brigade#332]
@mollymcleod and I were looking at the National Day call out as @hackyourcity was presenting. It looks like the page header rather than a call out banner.

Can we move it into a badge or another call out? Also, we shouldn't have the exclamation mark a different color.

**Comment by ondrae** [comment]
If anyone wants to do this while I'm gone,
the banner html is at https://github.com/codeforamerica/brigade/blob/master/templates/base.html#L48
and the css is https://github.com/codeforamerica/brigade/blob/master/static/css/style.css#L5

Should show up on live site a few minutes after the commit is made.
