### ISSUE TITLE
Color contrast on About page

### ISSUE THREAD

**Issue by mollymcleod** [codeforamerica/brigade#334]
Text on a dark colored background should be white. Also, centered text is hard to read.
![image](https://cloud.githubusercontent.com/assets/4099343/7501837/0d3c29ee-f3ec-11e4-9bf9-3ce161385cf2.png)

The blue buttons on the red and green backgrounds are hard to see. 
![image](https://cloud.githubusercontent.com/assets/4099343/7501839/164cd6dc-f3ec-11e4-960f-97db69fc15f8.png)
![image](https://cloud.githubusercontent.com/assets/4099343/7501844/1da8dcc8-f3ec-11e4-8c0a-ba5096b11fcd.png)

Try dark blue, light gray, or white background from the pattern library. 
![image](https://cloud.githubusercontent.com/assets/4099343/7501874/75bc4a8a-f3ec-11e4-8400-9b48e413d664.png)
![image](https://cloud.githubusercontent.com/assets/4099343/7501881/7f18211c-f3ec-11e4-8b13-45024b6341af.png)

**Comment by tdooner** [comment]
Although the biggest infractions are gone, we still have a blue-on-green button on that page. Keeping open.
