### ISSUE TITLE
Add a people page

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#341]
#### Description

We should showcase the people involved in the civic tech movement. There are many ways to participate and we should promote all of them. We'll make special sections and call outs on the Brigade page for them. Can happen for individual Brigades too.
- Commits to civic tech projects
- Attendance at hack nights
- Attendance at national events
- Mentions by Brigade twitter accounts

We can collect all of these events in the PeopleDB.

**Comment by ondrae** [comment]
Here is http://chihacknight.org/open-source-people.html for example.

I'm thinking having more of a top five for each the categories above.

**Comment by ondrae** [comment]
@migurski had a good idea that instead of automatically giving someone a badge, we notify the local Captain, so they can give them the badge. Community building notifications rather than bland bots telling you a cold fake "good job human".

**Comment by kmcurry** [comment]
+1

On Mon, Aug 17, 2015 at 6:49 PM, Andrew Hyder <notifications@github.com>
wrote:

> @migurski <https://github.com/migurski> had a good idea that instead of
> automatically giving someone a badge, we notify the local Captain, so they
> can give them the badge. Community building notifications rather than bland
> bots telling you a cold fake "good job human".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/brigade/issues/341#issuecomment-131985588>
> .
>



-- 
Kevin Curry
Virginia Beach, VA

Play 3Scape https://go.3scape.me
