### ISSUE TITLE
Make Map Javascript resilient to null geometries

### ISSUE THREAD

**Issue by migurski** [codeforamerica/brigade#343]
Three organizations (Code for Toronto, Open Elections, and Data SF) have [missing lat/lons in the organizations endpoint](http://www.codeforamerica.org/api/organizations.geojson), and Mapbox.js is choking on them. Needs to be resilient to missing data. 

/cc @brielleplump @ondrae.

**Comment by ondrae** [comment]
Right now we pass in the geojson directly in one call. https://github.com/codeforamerica/brigade/blob/master/templates/index.html#L56

Instead we'll need to loop through each organization and check for lat lng, then add it to the map.
