### ISSUE TITLE
Highlight projects being worked on by multiple Brigades

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#346]
@kbnammacher from Code for San Francisco had the good idea to surface projects that are being worked on by multiple Brigades.

On the /projects page, have a section to show off projects where the same repo, or forks, which are owned by multiple Brigades.

**Comment by ondrae** [comment]
SQL queries that may help
```
SELECT name  FROM project GROUP BY name  HAVING COUNT(name) >= 5;

SELECT name, organization_name FROM project WHERE name IN (SELECT name FROM project GROUP BY name HAVING COUNT(*) >= 10);
```

**Comment by ondrae** [comment]
Check this branch https://github.com/codeforamerica/brigade/tree/show-popular-projects-%23346which calls upon the CfAPI staging server running this branch https://github.com/codeforamerica/cfapi/tree/find-popular-projects-%23346

**Comment by ondrae** [comment]
We're getting more requests for this from our Brigade captains. 
```
So other then us all grouping up in new channels around specific "top 10 re-deployable brigade apps", @jesse would it be helpful if @hackyourcity's <http://www.codeforamerica.org/brigade/projects|project list> had the ability to sort by forks/stars? I'm trying to think of how (other then being plugged into slack channels with ya'll) a brigader would discover what projects have worked in X cities...

Like, I know our old single-page static  website was forked with 5+ brigades, but no way to easily discover that in the projects lists

Maybe if the project search had another tag like "deployable in your city" that was a tag adorned by the brigade elders once you thought it had 1. usage 2. repeatable 3. documentation 4. active support community.
```

**Comment by BretFisher** [comment]
:+1: 

Here's those same quotes in more redable format :)

>So other then us all grouping up in new channels around specific "top 10 re-deployable brigade apps", @jesse would it be helpful if @hackyourcity's <http://www.codeforamerica.org/brigade/projects|project list> had the ability to sort by forks/stars? I'm trying to think of how (other then being plugged into slack channels with ya'll) a brigader would discover what projects have worked in X cities...

>Like, I know our old single-page static  website was forked with 5+ brigades, but no way to easily discover that in the projects lists

>Maybe if the project search had another tag like "deployable in your city" that was a tag adorned by the brigade elders once you thought it had 1. usage 2. repeatable 3. documentation 4. active support community.

**Comment by tdooner** [comment]
Fritz is working on this now, but in a very different way. Going to close this.
