### ISSUE TITLE
Displaying and using Meetup.com data

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#347]
#### Description
We're busy working on [attendance tools](https://github.com/codeforamerica/brigade/issues/344) to accurately measure the participation in the civic technology movement.

What we want from attendance is names, emails, and participation. Building our own tools gets us this.

Meetup.com is the main tool our Brigades use to organize their events. http://code-for-america-brigade.meetup.com/

Meetup has an API. http://www.meetup.com/meetup_api/

We never wanted to use it, because you can't get emails from it. We can get RSVPs and attendance though. If we are okay with not having emails for all attendance, then Meetups tools become useful to us.

What if we gave Brigades the choice, use our custom built attendance tools OR Meetup's checkin features. We'll accept both into our PeopleDB.

We'd still be able to provide the Brigade organizers with incredibly useful metrics about their group's participation. We'd still have incredibly useful metrics of attendance across the whole civic tech movement.

We just wouldn't have as many emails signed up on our mailing list. I'm okay with that.

**Comment by ondrae** [comment]
@cbracy I think this is what our first versions will look like. We'll tell Brigade's to either use our tools, or Meetup.com's checkin service. Both will give us attendance data.

All of those groups will get useful attendance views.
![screen shot 2015-07-10 at 12 17 09 pm](https://cloud.githubusercontent.com/assets/595778/8627203/3da7dc0a-26fe-11e5-8cfb-59bcb671bdcd.png)

The group's that mostly use Meetup, we won't be able to give specific members attendance related Badges or whatever in the future.

**Comment by ondrae** [comment]
The only rub right now, is the weird way we have Meetup set up for all the groups. Some of them are under Hannah's account, some are under Preston's. I'll need to get API keys for both of them, to have permission to access attendance for the groups they control. Which is okay, just weird.

You said Meetup api changes were coming. I'd like to have one organizational account that has access to all of the Meetup groups.

**Comment by cbracy** [comment]
We actually consolidated all of our accounts so there should only be one
account you need to access. Michael Santus or Hannah will have details.

Catherine Bracy
Director of Community Organizing
Code for America
@cbracy | bracy@codeforamerica.org

*Use your skills for good. **Apply to be a 2016 Code for America fellow.
<http://www.codeforamerica.org/forms/fellowship/become-a-fellow/?source_codes=staff>*

**Comment by ondrae** [comment]
@wbushy started work on this at https://github.com/OpenTwinCities/cfapi_attendance_sync

**Comment by ondrae** [comment]
#### Description
For us to access attendance data, we need to have co-organizer access from our `brigade-info@codeforamerica.org` Meetup API key. We should do a big push for all of our Brigades to give our account co-organizer access.

#### Steps
1. We need to go and join all of the Brigades groups with our account. This can be done manually by visiting each group and joining. Perhaps we can use the api too.
2. We get the current organizers of the Brigades to add `Code for America Brigade` as a co-organizer.
3.  We can have the carrot that once they do, we'll start adding their attendance data to our tool. Perhaps we pay for it as well?

**Comment by ondrae** [comment]
I just manually joined each of these Brigades from our main account. We should ask each of them to make us "Code for America Brigade" at least an assistant organizer.

http://www.meetup.com/BetaNYC/
http://www.meetup.com/HacksHackersAfrica/
http://www.meetup.com/Code-for-Melbourne-Community-Drinks-Hacknight/
http://www.meetup.com/CodeForBoulder/
http://www.meetup.com/OpenBrazil/
http://www.meetup.com/Code-for-Dayton/
http://www.meetup.com/Code-for-Greensboro/
http://www.meetup.com/open_kawasaki/
http://www.meetup.com/Code-for-Maine/
http://www.meetup.com/code-for-nashville/
http://www.meetup.com/CodeforNRV/
http://www.meetup.com/Code-for-NoVA/
http://www.meetup.com/Code-for-Philly/
http://www.meetup.com/Code-for-San-Jose/
http://www.meetup.com/Code-for-South-Africa-Hackers/
http://www.meetup.com/Rhode-Island-Code-for-America-Brigade/
http://www.meetup.com/code-for-seoul/
http://www.meetup.com/Civic-hacking-Madison/
http://www.meetup.com/Open-Data-Monterrey/
http://www.meetup.com/Open-Government-Civic-Technology-Meetup-by-Open-Austin/

http://www.meetup.com/OK-Lab-Berlin/
http://www.meetup.com/OKLab-Wuppertal-Meetup/
http://www.meetup.com/datalove-OK-Lab-Ulm/
http://www.meetup.com/OK-Lab-Stuttgart-Meet-Up/
http://www.meetup.com/OKLab-Paderborn/
http://www.meetup.com/OK-Lab-Munster/
http://www.meetup.com/code-for-muenchen/
http://www.meetup.com/OK-Lab-Magdeburg/
http://www.meetup.com/OK-Lab-Leipzig/
http://www.meetup.com/OKLab-Koln-Meetup
http://www.meetup.com/OK-Lab-Karlsruhe/
http://www.meetup.com/OK-Lab-Jena/

http://www.meetup.com/cleveland-civic-hacking/
http://www.meetup.com/Open-Houston/
http://www.meetup.com/OpenLexington/
http://www.meetup.com/Open-Nebraska-Meetup/
http://www.meetup.com/Open-Pittsburgh-our-Regions-Code-for-America-Brigade/
http://www.meetup.com/Open-San-Diego/

**Comment by ondrae** [comment]
Skip all of this. We're going to separate out the Meetup rsvps from the attendance data. Read more at https://github.com/codeforamerica/cfapi/issues/243
