### ISSUE TITLE
Build an easy way to add metadata to projects

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#355]
#### Description
The [CfAPI](https://github.com/codeforamerica/cfapi) is our master list of civic tech projects. We've started a [Brigade wide civic tech projects page](http://codeforamerica.org/brigade/projects) way to find, search, and celebrate projects. It currently sucks. Before we can build a useful Projects page, we need to get project metadata for the majority of projects.

The metadata format we've decided on is [civic.json](https://github.com/codeforamerica/cfapi#civicjson). This idea came from [Beta.nyc](https://github.com/BetaNYC/civic.json) and [Chi Hack Night](https://github.com/open-city/civic-json-worker). We've currently got support for the following attributes, but are happy to add more.
```
{
    "status": "Production",
    "tags": ["slack", "bot", "integration", "python", "flask", "glossary", "dictionary"]
}
```

We should build a tool that makes it super easy for volunteers to add a civic.json file to their projects.

#### How
Lets build a form to create the civic.json file and then send a pull request to the project.

It could live at https://www.codeforamerica.org/brigade/projects/civicjson though it doesn't have to be hosted by CfA.

This form should let you:
1. Let you pick your organization
2. Choose your project from the list of that organizations project
3. Let you choose the projects `status`
4. Let you choose `tags` for the project

We should have hard coded `status` choices. We can debate these choices, yet I suggest we go with [this rough draft list](https://docs.google.com/document/d/1cLpofMbgiL2kb08U5R6X9UuPxGmzwle_hvtPaf8Ud38/edit). 

Tags could be more free from, with some helpful suggestions list in the form.

#### Schema
There is going to be a debate about the schema. [There always is](https://github.com/BetaNYC/civic.json/issues). Lets keep schema suggestions gated by having a verified use case. 

For example @ddie suggested that we add a `dataset` attribute as well. This could be used then to automatically show relevant projects for each dataset in the [Open Data Census](http://us-city.census.okfn.org/). Great idea. The [same request has been echoed](https://github.com/codeforamerica/cfapi/issues/145) by data.gov.

**Comment by GovInTrenches** [comment]
Other form fields we could add: 

1) what's the problem this project tried to solve 
2) who is doing the work [and what partners] 
3) What does the solution look like 
4) what stage is it in, what needs to be done and 
5) this is who I contact about the project

**Comment by ondrae** [comment]
@zmon has a project that uses [these columns](https://docs.google.com/spreadsheets/d/1tnW2fTcPEQG93oebrCfvjZw4Vjtn6vkzvqyovxebKlI/edit#gid=1497527024).

**Comment by youmustfight** [comment]
Hey all, put together an idea for extending the civic.json based on some feedback from non-technical/technical folks: 
https://gist.github.com/youmustfight/5173577d780ee6faa603

Also, I don't know if this is too much, but I had an idea for making a civic.json writer so non-technical people could do documentation? I imagine this would mean the JSON files would live off of Github, but perhaps we can utilize the github api to edit files on repos? Anyways, food for thought: https://marvelapp.com/76d23e

**Comment by ondrae** [comment]
@youmustfight WHAT that mock up is great. I didn't see it at the time. Wish I had cause here is mine prototype. http://brigade-staging.herokuapp.com/brigade/projects/14991/add-civic-json

its super rough draft and doesn't handle all the common errors yet.

I'm only supporting `status` and `tags` to start with.
Status or stages are described at http://www.codeforamerica.org/brigade/projects/stages

**Comment by ondrae** [comment]
If we need a way to speed up the update for that project quicker than the normal hourly update, refer to [this code](https://github.com/codeforamerica/cfapi/commit/903beeded46127ac325d762bc3e59b9afa61aada) as an experiment.
