### ISSUE TITLE
Create a test endpoint to POST attendance data too

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#356]
#### Description
We're asking people to [build their own attendance tools](https://github.com/codeforamerica/brigade/issues/352) and got a request from @wbushey for a POSTable test endpoint.

We should add a new route that accepts POSTs and returns the relevant response, yet doesn't forward on the checkin to the PeopleDB.

Should we also build out a whole test version of the peopledb to show real data? For now, to get timely access to your checkins, work with @ondrae

#### Files
app.py

#### Tasks
- [x] Add a `/brigade/test-checkin/` route
- [x] Have it return the same responses as the real checkin route

**Comment by patcon** [comment]
This seems to have disappeared. Can we have it back? :)
