### ISSUE TITLE
Check-in app - confirmation msg

### ISSUE THREAD

**Issue by Judy5000** [codeforamerica/brigade#363]
As a user, when I submit the completed form, I want a confirmation message or screen so I know my check-in was logged.

**Comment by ondrae** [comment]
Hey @Judy5000 there is a confirmation. A big green flag tag shows up and thanks you.
![screen shot 2015-08-31 at 11 22 22 am](https://cloud.githubusercontent.com/assets/595778/9586591/99357cba-4fd2-11e5-9e2c-e4df750226b8.png)

Then it does this really awkward animation to disappear to leave you with a blank check in form. I don't like it. The reason we did that was to take care of the use case when there is one laptop that everyone checks in on. We want it say thanks then be set up for the next person.

After we've had it going for a few weeks with the Cali Brigades though I want to get rid of the animation. I'm pretty sure I want to try out a Thank You as above, but then another link that you need to click to do another check in.
#### Files
checkin.html, app.py

#### Tasks
- [ ] Remove [jquery animation](https://github.com/codeforamerica/brigade/blob/master/templates/checkin.html#L20) from html
- [ ] Add a link to a clean check in form. Something like "Back to check in form"

**Comment by ondrae** [comment]
Okay did it. Try it out now.
