### ISSUE TITLE
Can we merge static content in to Cfa.org repo?

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#391]
Do we need a stand alone app to run the Brigade website? It might makes it easier for the Brigade staff to update.

Splitting it out may make it more confusing though, if there is still a Brigade repo.

If we do split it out, do we need a Brigade repo and app to serve the individual Brigade pages? Like https://www.codeforamerica.org/brigade/Code-for-San-Francisco/

**Comment by tdooner** [comment]
Gonna keep running with it as a separate site for now.
