### ISSUE TITLE
Design pass

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#398]
#### Description
Our MVPs of the Project Search page and the Civic Json builder are nigh. We need to do a design pass on them so that they are in a testable state.

#### Project Search
![screen shot 2015-12-08 at 10 24 39 am](https://cloud.githubusercontent.com/assets/595778/11664318/ec3c01d4-9d95-11e5-9786-eee0e0d37325.png)

#### Civic Json Builder
![screen shot 2015-12-07 at 5 07 53 pm](https://cloud.githubusercontent.com/assets/595778/11644951/1dab5b7a-9d05-11e5-8394-f7ca9dd47444.png)

**Comment by ondrae** [comment]
* Project Stages link isn't obvious. Have another one below stages that says "Want to learn what these mean?"

**Comment by mollymcleod** [comment]
Idea for project cards
![brigade-projects-12 07](https://cloud.githubusercontent.com/assets/4099343/11644827/4592fc8e-9d04-11e5-91bb-09687f38984c.png)

**Comment by ondrae** [comment]
The first draft of the civic json builder for @mollymcleod review
![screen shot 2015-12-07 at 5 07 53 pm](https://cloud.githubusercontent.com/assets/595778/11644951/1dab5b7a-9d05-11e5-8394-f7ca9dd47444.png)
