### ISSUE TITLE
Travis might be leaking our env variables

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#405]
https://travis-ci.org/codeforamerica/brigade has some of our test env variables being reported to std out.

**Comment by tmaybe** [comment]
There was an env variable in the settings for the brigade project on the travis site. I deleted it from there and added a stand-in suitable for testing to the travis.yml file: https://github.com/codeforamerica/brigade/commit/6c29f33d2b7f9276b77a035f5dc8a40d74758623
