### ISSUE TITLE
Civic Json Error

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#412]
I manually went to the url http://www.codeforamerica.org/brigade/Code-for-America/projects/bizfriendly-web/add-civic-json with the intention of overwriting the existing civic.json file.

I got this error
> Branch add-civic-json-file not found

**Comment by ondrae** [comment]
http://www.codeforamerica.org/brigade/Code-for-America/projects/ebt-near-me/add-civic-json

**Comment by tmaybe** [comment]
I thought maybe that branch creation happened asynchronously, like fork creation does, but [that doesn't appear to be the case](https://developer.github.com/v3/git/refs/#create-a-reference).
