### ISSUE TITLE
search by city or who uses the project

### ISSUE THREAD

**Issue by cleechtech** [codeforamerica/brigade#423]
It would be cool to search projects by city or who the project is "used by". Currently only filters by the stage the project is in:

![screen shot 2015-12-16 at 4 20 05 pm](https://cloud.githubusercontent.com/assets/3578908/11857862/f0462e9a-a410-11e5-9516-8af75e1ccf35.png)

**Comment by ondrae** [comment]
Hey Connor. Good feedback, its harder than it should be to do that.

Right now, you can either search for your group like http://www.codeforamerica.org/brigade/projects?q=Open+Oakland or there is a specific url for your group at http://www.codeforamerica.org/brigade/Open-Oakland/projects.

Searching for a city mostly works fine.

**Comment by cleechtech** [comment]
Maybe we should just throw a 'won't fix' label on here. Closing the issue!
