### ISSUE TITLE
Line up Issues section with others on individual brigade pages

### ISSUE THREAD

**Issue by verythorough** [codeforamerica/brigade#430]
The Issues section has a different layout class (layout-breve) from the other sections on the page (layout-semibreve).  This leaves uneven margins on wider screens.

![brigade-margins](https://cloud.githubusercontent.com/assets/6111186/12131634/4a1d2c6c-b3c9-11e5-9439-d8e44fd1caff.png)

**Comment by ondrae** [comment]
All lined up. Thanks @verythorough 
![screen shot 2016-01-05 at 10 02 18 pm](https://cloud.githubusercontent.com/assets/595778/12135991/0537a080-b3f8-11e5-99fe-27cda3544974.png)
