### ISSUE TITLE
Embeddable iframe source issue

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/brigade#437]
Looks like the iframe source at `/brigade/projects/embed` doesn't include the `codeforamerica.org` domain. The iframe embed will work on codeforamerica.org, but not on other sites.

**Comment by ondrae** [comment]
This is in reference to the embed version of the project search on the https://github.com/codeforamerica/brigade/tree/react-project-search branch.

**Comment by cweems** [comment]
@graysonwright @ondrae Went ahead and took care of this in #439!

**Comment by ondrae** [comment]
:boom:
