### ISSUE TITLE
style.codeforamerica.org uses an invalid security certificate

### ISSUE THREAD

**Issue by groovecoder** [codeforamerica/brigade#448]
style.codeforamerica.org uses an invalid security certificate. The certificate expired on October 8, 2016 at 6:59 PM. The current time is January 27, 2017 at 10:15 PM.

This breaks the site when running HTTPS Everywhere.

And serving insecure display content opens the site up to MITM manipulation.

**Comment by dcloud** [comment]
Looking at it right now, it appears that it is serving up a wildcard certificate for *.heroku.com, rather than one for codeforamerica.org. I believe following the steps outlined at https://devcenter.heroku.com/articles/ssl should correct the issue.

**Comment by tdooner** [comment]
Cannot reproduce, I'll assume we must have fixed it.
