### ISSUE TITLE
Edit About Us tab content 

### ISSUE THREAD

**Issue by GovInTrenches** [codeforamerica/brigade#452]
Replace page with the following content 

'We’re a national network of community organizers & technologists who are putting technology to work for the benefit of our local communities. 

Our Brigades meet regularly to build, share and learn about tools to create, support, and serve the public good.

We're thousands of designers, academic researchers, data journalists, activists, policy wonks, web developers and curious citizens who want to make our city more just, equitable, transparent and delightful to live in through data, design and technology.

Come join us!'

**Comment by fritzjooste** [comment]
The about page has been updated with the new text.
