### ISSUE TITLE
Improve Brigade profile map

### ISSUE THREAD

**Issue by fritzjooste** [codeforamerica/brigade#480]
Based on some user testing, the brigade profile map on the home page is a little tricky to navigate. It's not clear what the map is of, it involves too much zooming and dragging, there's no ability to search or filter on the map, and the brigade intro text takes up too much screen space on desktop.

- [x] Update map to only show Brigades in the US
- [x] Zoom map to US at the start
- [x] Add map search control
- [x] Add hover tooltips with Brigade names
- [x] Link to Code for All website

**Comment by GovInTrenches** [comment]
We can probably take out all the international brigades from this map. I mean, they exist and we should link to Code for All somewhere - but for our users it's probably going to just be the US.

**Comment by fritzjooste** [comment]
I agree. I'll add that as a to do list item.
