### ISSUE TITLE
500 error when clicking "more projects" on Brigade projects page

### ISSUE THREAD

**Issue by fritzjooste** [codeforamerica/brigade#498]
For example, on [Open Oakland's project page](http://brigade.codeforamerica.org/brigade/Open-Oakland/projects), clicking on the [More Projects](http://brigade.codeforamerica.org/brigade/Open-Oakland/projects?page=2) button on the bottom right of the page returns a 500 error.

**Comment by ondrae** [comment]
Hmm, its supposed to make an api request to http://api.codeforamerica.org/api/organizations/Open-Oakland/projects?page=2

**Comment by tdooner** [comment]
Cannot reproduce any longer.
